language: cpp
before_install:
# For Qt 5.7
- sudo add-apt-repository --yes ppa:beineri/opt-qt571-trusty

- sudo apt-get update -qq

# For CMake

- mkdir $HOME/usr
- export PATH="$HOME/usr/bin:$PATH"
- wget https://cmake.org/files/v3.12/cmake-3.12.2-Linux-x86_64.sh
- chmod +x cmake-3.12.2-Linux-x86_64.sh
- ./cmake-3.12.2-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license

install:
 - sudo apt-get install -qq qt57base qt57multimedia qt57script
 - source /opt/qt57/bin/qt57-env.sh

before_script:
  - mkdir build
  - cd build
  - cmake ../ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX= $HOME/output || cat /home/travis/build/kegarlv/QtTrd/CMakeFiles/CMakeOutput.log

script: make

before_deploy:
  - cd $HOME
  - tar cvfz output.tgz output/

deploy:
  provider: releases
  user: $DEPLOY_USERNAME
  password: $DEPLOY_PASSWORD
  file: $HOME/output.tgz
  skip_cleanup: true
  on:
    branch: test_travis
