language: cpp
before_install:
# For Qt 5.7
- sudo add-apt-repository --yes ppa:beineri/opt-qt571-trusty

- sudo apt-get update -qq

install:
 - sudo apt-get install -qq qt57base qt57multimedia qt57script
 - source /opt/qt54/bin/qt57-env.sh


script: cmake . -DCMAKE_BUILD_TYPE=Release && make
